export const SET_AUDIO = 'SET_AUDIO'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_SHOWPLAYER = 'SET_SHOWPLAYER'

export const SET_CURRENT_IMG = 'SET_CURRENT_IMG'

export const SET_CURRENT_SONG_TITLE = 'SET_CURRENT_SONG_TITLE'
